name = "lms-auth-redirector"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[ kv_namespaces ]]
binding = "store"
id = "91a86d29de3e4349be322ef170d4436d"
preview_id = "39417a004e5644f5a3eba61abbfd7cf6"
