#########################################################################
#ID     Suffix          Mime Content-Type               Server File Type#
#########################################################################
spt     spt             audio/x-sb-spotify              audio
spc     spc             audio/x-sb-spotify-connect      audio
